# Generated by Django 4.1.5 on 2023-01-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="getData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=50)),
                ("lastname", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("test", models.IntegerField(default=0)),
                (
                    "testchoices",
                    models.CharField(
                        choices=[("yes", "yes"), ("no", "no")], max_length=3
                    ),
                ),
            ],
        ),
    ]
