# Generated by Django 4.1.5 on 2023-01-08 16:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MyApi", "0002_getdata_date_created_getdata_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="getdata",
            name="date_created",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2023, 1, 8, 22, 20, 4, 384980)
            ),
        ),
        migrations.AlterField(
            model_name="getdata",
            name="email",
            field=models.EmailField(default="error@gmail.com", max_length=254),
        ),
        migrations.AlterField(
            model_name="getdata",
            name="firstname",
            field=models.CharField(default="first_name", max_length=50),
        ),
        migrations.AlterField(
            model_name="getdata",
            name="image",
            field=models.ImageField(
                default="static/foodimages/1072416.jpg",
                upload_to="MyApi/static/foodimages",
            ),
        ),
        migrations.AlterField(
            model_name="getdata",
            name="lastname",
            field=models.CharField(default="last_name", max_length=50),
        ),
    ]
