# Generated by Django 4.1.5 on 2023-01-08 16:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MyApi", "0003_alter_getdata_date_created_alter_getdata_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="getdata",
            name="date_created",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2023, 1, 8, 22, 21, 3, 960877)
            ),
        ),
        migrations.AlterField(
            model_name="getdata",
            name="image",
            field=models.ImageField(
                default="static/foodimages/1072416.jpg", upload_to="static/foodimages"
            ),
        ),
    ]
