# Generated by Django 4.1.5 on 2023-01-08 16:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MyApi", "0006_alter_getdata_date_created_alter_getdata_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="getdata",
            name="date_created",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2023, 1, 8, 22, 26, 17, 39672)
            ),
        ),
        migrations.AlterField(
            model_name="getdata",
            name="image",
            field=models.ImageField(
                default="static/foodimages/1072416.jpg", upload_to="static/foodimages/"
            ),
        ),
    ]
