# Generated by Django 4.1.5 on 2023-01-08 17:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MyApi", "0009_alter_getdata_date_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="getdata",
            name="date_created",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2023, 1, 8, 22, 44, 18, 464815)
            ),
        ),
        migrations.AlterField(
            model_name="getdata",
            name="image",
            field=models.ImageField(
                default="foodimages/1072416.jpg", upload_to="foodimages/"
            ),
        ),
    ]
